### ISSUE TITLE
Less Interactive

### ISSUE THREAD

**Issue by ayushsharma031009** [metakgp/travel-buddy#1]
I think we can enhance the UI of the project. The background color, text style,  navbar etc should be more interactive .
I can use css and js to enhance it's frontend overall.

**Comment by harshkhandeparkar** [comment]
@ayushsharma031009 Please let us know the specific things you are suggesting to change. Perhaps a design mockup so we can give our inputs and decide together. Try not to make any pull requests or large changes before approval. You can discuss in #projects on our slack - https://slack.metakgp.org.

**Comment by ayushsharma031009** [comment]
for the interactive ui we can add hover effects, animations and colors in the page for example when we hover on the buttons - the size of button increases or color of button changes also we can add after effects like after clicking a link we can change the color of link (text on the button). Something like this

**Comment by saharsh-agrawal** [comment]
Refer to #2 and #3 to discuss both things seperately.
