### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by ayushsharma031009** [metakgp/travel-buddy#3]
A white background is too simple, to attract users we can change background image and colors

**Comment by harshkhandeparkar** [comment]
@ayushsharma031009 Do you have any suggestions for this?

**Comment by ayushsharma031009** [comment]
![Screenshot 2024-11-25 103147](https://github.com/user-attachments/assets/7c1d7b2a-7f17-48f3-bb18-974fec73eb85)
here we can add background images like -

**Comment by harshkhandeparkar** [comment]
Hmm, that works, but the text should be clearly visible, and the image should be copyright-free.

**Comment by ayushsharma031009** [comment]
yes i know that much i have lot of options for background image , colors and designs. For the copyright issue , we can use unsplash and many other sites for copyright free images.

**Comment by saharsh-agrawal** [comment]
Please refer to #9 for UI changes

**Comment by saharsh-agrawal** [comment]
Please refer to #9  for UI changes.
