### ISSUE TITLE
We have to work alot on UI/UX. 

### ISSUE THREAD

**Issue by madhavv-xd** [metakgp/travel-buddy#6]

**Comment by saharsh-agrawal** [comment]
Can you point out a few of the big changes that you want to make?

**Comment by madhavv-xd** [comment]
Is the website hosted ? If not then I'll look up later.

**Comment by Waqibsk** [comment]
i am planning to implement a clean black and white theme to the whole website which will make it visually appealing. here is a sample home page ...
![Screenshot (18)](https://github.com/user-attachments/assets/b1224553-e231-4f06-a493-d72b994da72f)
please let me know if i should continue with it

**Comment by harshkhandeparkar** [comment]
> i am planning to implement a clean black and white theme to the whole website which will make it visually appealing. here is a sample home page ... ![Screenshot (18)](https://private-user-images.githubusercontent.com/162541991/392438912-b1224553-e231-4f06-a493-d72b994da72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTUwMDcsIm5iZiI6MTczMzQxNDcwNywicGF0aCI6Ii8xNjI1NDE5OTEvMzkyNDM4OTEyLWIxMjI0NTUzLWUyMzEtNGYwNi1hNDkzLWQ3MmI5OTRkYTcyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxNjA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2UyZTZlZGY5MDMwNWI0MDIwZWFkNGVkYmRjOGFmODRjMTkyNzQ5MDMzNjJlYjBhNTllM2E4Y2MxNWRiYzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9PLxbzCtwYD3JDWE-nqRp0_mEX4YeXecA_fGkKiSO6s) please let me know if i should continue with it

I think we should focus on features first.

**Comment by harshkhandeparkar** [comment]
> Is the website hosted ? If not then I'll look up later.

Please open a more specific issue with details once you do. Closing this one since it doesn't have any description.
