### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by Archi-shaw** [metakgp/travel-buddy#9]
1. Color scheme: inconsistent and basic; lacks vibrancy and interactivity (e.g., no hover effects).
2. Typography: Small font size for footer text; poor spacing and readability.
3. Buttons: Generic labels; lack descriptive icons or hover feedback.
4. Footer Link: "Contribute to the project" link lacks emphasis and visibility.
5. Visual Appeal: illustrations or icons to make the UI engaging.

**Comment by harshkhandeparkar** [comment]
1. Can you suggest a color scheme or a design?
2. Can you make a PR to fix it?
3. Can you elaborate what you mean by generic labels? The other suggestions are fine, can be done.
4. How do you think we can make it better?
5. Where?

**Comment by Archi-shaw** [comment]
Yes I can fix it 
1. Minimalist icons for **_trains_** and _**trips**_ that are easily recognizable.
2. Add hover effects to the "Trips" and "Trains" buttons, like a glowing border or subtle shadow.
3.Use subtle gradients on buttons or backgrounds (e.g., sky blue fading into white)
4. We can use background images here. Below are some options I’ve found, but feel free to share any images you’d like to use!
![travel-landscape-dreamy-aesthtetic](https://github.com/user-attachments/assets/0eac0df0-4010-4f1c-a6fe-9405d26afff4)
![full-shot-people-walking-together](https://github.com/user-attachments/assets/eedad5ce-dde1-4ea3-a3da-0dcf9210da21)
![bridge-surrounded-by-greenery-clear-sky-garden-route-national-park (1)](https://github.com/user-attachments/assets/cc5112d4-8a17-454c-8102-6447909be8c1)
![couple-looking-map (1)](https://github.com/user-attachments/assets/4b46fd6a-4639-4121-8869-e74715e81b84)
5. Generic labels" refer to button texts like "Trips" and "Trains" that are not descriptive enough. Users may not instantly understand what action or feature these buttons represent. Here's how they can be improved:
"Trips" → "Plan a Trip"
"Trains" → "Find Train Buddies" Adding these descriptions makes the buttons more intuitive and user-friendly.
6. Add icons to buttons and the footer for visual hierarchy.
7. Make the "Contribute to the project" link stand out by styling it as a button or using bold, vibrant colors.
8. Specific areas to focus on are background,Footer as well as buttons

**Comment by Archi-shaw** [comment]
@harshkhandeparkar Am I assigned for the issue?

**Comment by saharsh-agrawal** [comment]
There is no such assignment to an issue as such. You can start working on any issue and send PRs.

1,2,3 are fine.
4. Yes, but remember, both are to find partners, none are to actually "plan" a trip
5, 6, 7. Yes, maybe. Someone is already working on a header and footer and you should have a look into that and work there.

**Comment by harshkhandeparkar** [comment]
@Archi-shaw I would suggest you to open specific issues for the problems and solutions discussed above and greenlit by @saharsh-agrawal. We can assign you to the specific issues and review your PRs separately. Making one PR per problem/solution would be organized and easy to review.

**Comment by harshkhandeparkar** [comment]
You can close this issue once you open the sub-issues. And it would be better to use our slack - https://slack.metakgp.org #projects channel for this kind of discussion. It would be faster and easier there.
